# docs: https://www.rainbond.com/docs/installation/install-with-dind


version: '3.8'

services:
  rainbond:
    image: registry.cn-hangzhou.aliyuncs.com/goodrain/rainbond:${APP_VERSION}
    container_name: ${APP_NAME}
    ports:
      - '${APP_HTTP_PORT}:7070'
      - '${APP_HTTPS_PORT}:8443'
      - '80:80'
      - '443:443'
      - '6060:6060'
    privileged: true
    environment:
      - ENABLE_CLUSTER=true
      - EIP=$APP_URL
    volumes:
      - '~/.ssh:/root/.ssh'
      - '~/rainbonddata:/app/data'
      - '/opt/rainbond:/opt/rainbond'
      - '~/dockerdata:/var/lib/docker'

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  rainbond:
